set_property PACKAGE_PIN D19 [get_ports {key_num[1]}]
set_property PACKAGE_PIN D20 [get_ports {key_num[0]}]
set_property PACKAGE_PIN L20 [get_ports key_done]
set_property PACKAGE_PIN H16 [get_ports clk]
set_property PACKAGE_PIN M20 [get_ports rst_n]
set_property PACKAGE_PIN L15 [get_ports led]
set_property PACKAGE_PIN B19 [get_ports rx]
set_property PACKAGE_PIN A20 [get_ports tx]

set_property IOSTANDARD LVCMOS33 [get_ports {key_num[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_num[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports key_done]
set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]

set_property PACKAGE_PIN Y9 [get_ports signal_done]
set_property IOSTANDARD LVCMOS33 [get_ports signal_done]

set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led2]
set_property IOSTANDARD LVCMOS33 [get_ports led3]
set_property IOSTANDARD LVCMOS33 [get_ports led4]
set_property PACKAGE_PIN R14 [get_ports led1]
set_property PACKAGE_PIN P14 [get_ports led2]
set_property PACKAGE_PIN N16 [get_ports led3]
set_property PACKAGE_PIN M14 [get_ports led4]

set_property PACKAGE_PIN W9 [get_ports BL]
set_property PACKAGE_PIN W18 [get_ports CSX]
set_property PACKAGE_PIN Y6 [get_ports RWX]
set_property PACKAGE_PIN W19 [get_ports WRX]
set_property PACKAGE_PIN U7 [get_ports lcd_rst]
set_property PACKAGE_PIN Y8 [get_ports {data_lcd[15]}]
set_property PACKAGE_PIN B20 [get_ports {data_lcd[14]}]
set_property PACKAGE_PIN W8 [get_ports {data_lcd[13]}]
set_property PACKAGE_PIN Y17 [get_ports {data_lcd[12]}]
set_property PACKAGE_PIN U18 [get_ports {data_lcd[11]}]
set_property PACKAGE_PIN U19 [get_ports {data_lcd[10]}]
set_property PACKAGE_PIN W10 [get_ports {data_lcd[9]}]
set_property PACKAGE_PIN F19 [get_ports {data_lcd[8]}]
set_property PACKAGE_PIN V10 [get_ports {data_lcd[7]}]
set_property PACKAGE_PIN F20 [get_ports {data_lcd[6]}]
set_property PACKAGE_PIN V8 [get_ports {data_lcd[5]}]
set_property PACKAGE_PIN Y7 [get_ports {data_lcd[4]}]
set_property PACKAGE_PIN U8 [get_ports {data_lcd[3]}]
set_property PACKAGE_PIN W6 [get_ports {data_lcd[2]}]
set_property PACKAGE_PIN V7 [get_ports {data_lcd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports BL]
set_property IOSTANDARD LVCMOS33 [get_ports CSX]
set_property IOSTANDARD LVCMOS33 [get_ports DCX]
set_property IOSTANDARD LVCMOS33 [get_ports RWX]
set_property IOSTANDARD LVCMOS33 [get_ports WRX]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rst]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lcd[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lcd[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lcd[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lcd[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lcd[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lcd[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lcd[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lcd[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lcd[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lcd[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lcd[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lcd[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lcd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lcd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lcd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lcd[0]}]

set_property PACKAGE_PIN V6 [get_ports DCX]


set_property PACKAGE_PIN C20 [get_ports {data_lcd[0]}]
